POST http://localhost:3000/register/
Content-Type:application/json

{
  "username": "Dhoni",
  "name": "Ms Dhoni",
  "password": "dhoni123",
  "gender": "male",
  "location": "India"
}

POST http://localhost:3000/login/
Content-Type:application/json

{
  "username": "Dhoni",
  "password": "dhoni@123"
}

PUT http://localhost:3000/change-password/
Content-Type:application/json

{
  "username": "Dhoni",
  "oldPassword": "dhoni123",
  "newPassword": "dhoni@123"
}